# sitemap settings

template: sitemap.twig
xml_template: sitemap_xml.twig

ignore:
  - /galeries
  - /galerie/.*

## ignore by "slug" of contenttype
#ignore_contenttype:
#  - pages

## listing routes (contenttype_slug: route_name)
#listing_routes:
#  le_centre: le_centre
#  join_us: join_us

# ignore listing templates
#ignore_listing: false

## ignore images (by default the sitemap contains links to images)
ignore_images: false

## when ignore_listing is not = true: listings templates may not exist yet may contain child pages.
## add path will keep listing visible in tree but remove its link.
#remove_link:
#  - /pages
